apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'ast2vec'
        static_configs:
          - targets: ['ast2vec:8082']
---
apiVersion: v1
kind: Pod
metadata:
  name: ast2vec
  labels:
    pod: ast2vec
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
  - name: ast2vec
    image: inpefess/ast2vec
    ports:
    - containerPort: 8080
    - containerPort: 8082
    env:
    - name: REDIS_HOST
      value: ast2vec
  - name: prometheus
    image: prom/prometheus
    ports:
    - containerPort: 9090
    volumeMounts:
      - name: config-vol
        mountPath: /etc/config
  - name: grafana
    image: grafana/grafana
    ports:
    - containerPort: 3000
  volumes:
    - name: config-vol
      configMap:
        name: prometheus-config
        items:
          - key: prometheus.yml
            path: prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  name: ast2vec
spec:
  type: NodePort
  selector:
    pod: ast2vec
  ports:
  - name: ast2vec
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
